use_frameworks!

target 'MultiPlatformFramework_Example' do
  pod 'MultiPlatformFramework', :path => '../'
  pod 'RealmSwift'

  target 'MultiPlatformFramework_Tests' do
    inherit! :search_paths

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end

  end
end
