Pod::Spec.new do |s|
  s.name             = 'MultiPlatformFramework'
  s.version          = '0.1.0'
  s.summary          = 'An iOS, watchOS and tvOS framework'
  s.description      = <<-DESC
                        An iOS, watchOS and tvOS framework
                       DESC

  s.homepage         = 'https://github.com/miguelcampiao/MultiPlatformFramework'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Miguel Campião' => 'miguel.campiao@gmail.com' }
  s.source           = { :git => 'https://github.com/miguelcampiao/MultiPlatformFramework.git', :tag => s.version.to_s }

  s.ios.deployment_target = '10.2'
  s.watchos.deployment_target = '3.1'
  s.tvos.deployment_target = '10.1'

  s.source_files = 'MultiPlatformFramework/Classes/**/*'
  s.frameworks = 'Foundation'
  s.dependency 'RealmSwift'
  s.source_files = 'MultiPlatformFramework/Classes/*.{swift}'

end